- hosts: debian
  roles:
    - name: debian_server
      become: yes
    - name: geerlingguy.docker
      become: yes
    - name: portainer
      become: yes
    - name: homeassistant_container
      become: yes
