---
- name: install webdav
  tags: install
  apt:
    pkg:
      - nginx-light
      - libnginx-mod-http-dav-ext

- name: copy site configuration
  tags: webdav
  copy:
    src: files/default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
