---
- name: create prometheus node exporter source directory
  become: true
  tags: install
  file:
    path: /opt/node_exporter
    state: directory

- name: download prometheus node exporter
  become: true
  tags: install
  get_url:
    dest: /opt/node_exporter/node_exporter-{{ prometheus_node_version }}.tar.gz
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_version }}/node_exporter-{{ prometheus_node_version }}.linux-{{ prometheus_node_arch }}.tar.gz

- name: unarchive prometheus node exporter
  become: true
  tags: install
  unarchive:
    dest: /opt/node_exporter/
    src: /opt/node_exporter/node_exporter-{{ prometheus_node_version }}.tar.gz
    remote_src: yes
    creates: /opt/node_exporter/node_exporter-{{ prometheus_node_version }}.linux-{{ prometheus_node_arch }}/node_exporter

- name: Create a symbolic link
  become: true
  tags: install
  ansible.builtin.file:
    src: /opt/node_exporter/node_exporter-{{ prometheus_node_version }}.linux-{{ prometheus_node_arch }}
    dest: /opt/node_exporter/current
    state: link

- name: copy systemd service file
  become: true
  tags: install
  copy:
    src: files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"

- name: enable and start prometheus node service
  become: true
  tags: install
  systemd:
    daemon_reload: yes
    daemon_reexec: yes
    state: started
    enabled: yes
    name: node_exporter.service
