---
- name: Update all packages
  tags: os
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    autoremove: yes

- name: Install base requirements
  tags: os
  become: yes
  apt:
    pkg:
      - git
      - vim
