---
- name: update all packages
  tags: os
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    autoremove: yes

- name: install base requirements
  tags: os
  become: yes
  apt:
    pkg:
      - git
      - vim

- name: generate an SSH keypair
  tags: os
  openssh_keypair:
    path: /home/pi/.ssh/id_rsa

- import_tasks: raspiconfig.yml
