---
- name: Create nginxproxymanager directory
  ansible.builtin.file:
    path: /srv/nginxproxymanager
    state: directory
    mode: "0755"

- name: Create nginxproxymanager container
  community.docker.docker_container:
    name: nginxproxymanager
    image: jc21/nginx-proxy-manager:{{ nginxproxymanager_tag }}
    state: started
    restart_policy: "unless-stopped"
    container_default_behavior: "no_defaults"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /srv/nginxproxymanager/data:/data
      - /srv/nginxproxymanager/letsencrypt:/etc/letsencrypt
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
      homepage.group: Home
      homepage.name: Nginx Proxy Manager
      homepage.icon: nginx-proxy-manager.png
      homepage.href: http://192.168.1.150:81
      homepage.description: Proxy for all local sites
