---
- name: Create docker volume
  community.docker.docker_volume:
    name: portainer_data

- name: Create portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:{{ portainer_tag }}
    state: started
    restart_policy: "always"
    container_default_behavior: "no_defaults"
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
      homepage.group: Home
      homepage.name: Portainer
      homepage.icon: portainer.png
      homepage.href: https://portainer.atlocal.duckdns.org
      homepage.description: Docker container dashboard
