---
- name: Install python3-docker package
  apt:
    pkg:
      - python3-docker

- name: Create docker volume
  community.docker.docker_volume:
    name: portainer_data

- name: Create portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:{{ portainer_version }}
    state: started
    restart_policy: "always"
    container_default_behavior: "no_defaults"
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
