---
- name: install python
  import_tasks: python.yml

- name: install hyperion from deb
  tags: install
  become: true
  apt:
    deb: "{{ hyperion_deb }}"
    state: present

- name: install inotify-tools
  tags: v4l2
  become: true
  apt:
    pkg:
      - inotify-tools
      - libcec4 # required by hyperion.ng 2.0.0-alpha.8

- name: copy v4l2-settings
  tags: v4l2
  become: true
  copy:
    src: files/v4l2-settings.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"

- name: copy v4l2-settings service
  tags: v4l2
  become: true
  copy:
    src: files/v4l2-settings.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: enable and start v4l2-settings service
  tags: v4l2
  become: true
  systemd:
    daemon_reload: yes
    daemon_reexec: yes
    state: started
    enabled: yes
    name: v4l2-settings.service

- name: copy custom effects
  tags: hyperion
  become: true
  copy:
    src: files/custom-effects/
    dest: /usr/share/hyperion/effects/
    owner: root
    group: root
    mode: "0644"

- name: copy hyperion script
  tags: hyperion
  become: true
  copy:
    src: files/hyperion.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"

- name: copy hyperion service
  tags: hyperion
  become: true
  copy:
    src: files/hyperion@.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: enable and start hyperion service
  tags: hyperion
  become: true
  systemd:
    daemon_reload: yes
    daemon_reexec: yes
    state: started
    enabled: yes
    name: hyperion@pi.service
