---
- name: create prometheus directory
  tags: install
  become: yes
  file:
    path: /opt/prometheus
    state: directory

- name: download prometheus {{ prometheus_version }}
  tags: install
  become: yes
  get_url:
    dest: /opt/prometheus/prometheus-{{ prometheus_version }}.tar.gz
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}.tar.gz

- name: unarchive prometheus {{ prometheus_version }}
  tags: install
  become: yes
  unarchive:
    dest: /opt/prometheus/
    src: /opt/prometheus/prometheus-{{ prometheus_version }}.tar.gz
    remote_src: yes
    creates: /opt/prometheus/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}/prometheus
    owner: pi
    group: pi

- name: Create a symbolic link
  tags: install
  become: yes
  ansible.builtin.file:
    src: /opt/prometheus/prometheus-{{ prometheus_version }}.linux-{{ prometheus_arch }}
    dest: /opt/prometheus/current
    owner: pi
    group: pi
    state: link

- name: copy config file
  tags: install
  become: yes
  copy:
    src: files/prometheus.yml
    dest: /opt/prometheus/current/prometheus.yml
    owner: pi
    group: pi
    mode: '0644'

- name: copy systemd service file
  tags: install
  become: yes
  copy:
    src: files/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: enable and start prometheus service
  tags: install
  become: yes
  systemd:
    daemon_reload: yes
    daemon_reexec: yes
    state: started
    enabled: yes
    name: prometheus.service
